### ISSUE TITLE
buggy ouput

### ISSUE THREAD

**Issue by thierryjanssens** [timkahlke/BASTA#10]
Dear Tim,

when running the basta commands (from a cloned git in the envs bin folder) I get the following buggy uotpu when downloading the taxdump and databse association files:
Traceback (most recent call last):

  File "./basta", line 117, in <module>
    main.run_basta(args)
  File "./../basta/BastaMain.py", line 71, in run_basta
    self._basta_download(args)
  File "./../basta/BastaMain.py", line 147, in _basta_download
    dutils.down_and_check(args.ftp,map_file,args.directory)
  File "./../basta/DownloadUtils.py", line 56, in down_and_check
    self.down(ftp,md5,out_dir)
NameError: global name 'self' is not defined

The files are downloaded, however.

When running a primary trial analysis a full blown error appears:
$/data/anaconda3/envs/basta/bin/BASTA/bin/basta sequence ./data/assembly-nt.tab ./results/assembly-lca.test gb

Traceback (most recent call last):
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/basta", line 9, in <module>
    from basta import BastaMain as bm
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/BastaMain.py", line 6, in <module>
    import plyvel
ModuleNotFoundError: No module named 'plyvel'

The lacking module has been installed.
$ conda list

...
plyvel                    0.8                      py27_0    bnoon
...

I hope you can help.

Kind regards,

Thierry

**Comment by timkahlke** [comment]
Hi Thierry,

1. The first error is my fault: I did a buggy commit of the DownloadUtils. Please do a "git pull" in the basta directory.

2. I'm not sure why conda didn't load plyvel. Did you activate the environment before using basta? Try "source activate py27" first and then try "bin/basta taxonomy". If that works and downloads the taxonomy without warnings/errors try the download command.

**Comment by thierryjanssens** [comment]
Hi Tim,

thank you for your swift reply.

Indeed, I was running the command from jupyter notebook, outside the environment I created. 

I ran the same code again:

$/data/anaconda3/envs/basta/bin/BASTA/bin/basta sequence ./data/assembly-nt.tab ./results/assembly-lca.test gb[BASTA ERROR] Couldn't find complete_taxa.db in /data/anaconda3/envs/basta/bin/BASTA/taxonomy. Did you run initial 'basta download'?

After install I have run already:
$/data/anaconda3/envs/basta/bin/BASTA/bin/basta taxonomy
/data/anaconda3/envs/basta/bin/BASTA/bin/basta download gb
/data/anaconda3/envs/basta/bin/BASTA/bin/basta download protein

and the 
$ls /data/anaconda3/envs/basta/bin/BASTA/taxonomy

(basta) [user@hostname$ ls
nucl_gb.accession2taxid.gz  prot.accession2taxid.gz  taxdump.tar.gz

Is it maybe the name of the environment? Do we have to stick to the py27 name or can we use a custom name?

regards,

Thierry

**Comment by timkahlke** [comment]
The problem is that BASTA downloaded the files but didn't create the needed databases because of the initial error. You will have to run the taxonomy and download command again unfortunately.

**Comment by timkahlke** [comment]
If everything goes well the taxonomy folder should also contain a database folder for the taxonomy (complete_taxonomy.gb) and for the mappings that you downloaded/imported.

**Comment by thierryjanssens** [comment]
Dear Tim,

thank you for your swift reply.
Upon git pull still no database were created.

(basta) [user@hostname BASTA]$ git pull
remote: Counting objects: 4, done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/timkahlke/BASTA
   effd024..03e3e90  master     -> origin/master
Updating effd024..03e3e90
Fast-forward
 basta/DownloadUtils.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
(basta) [user@hostname BASTA]$ /data/anaconda3/envs/basta/bin/BASTA/bin/basta taxonomy

#### Downloading and processing NCBI taxonomy files


# [BASTA STATUS] Download taxonomy files

# [BASTA STATUS] (Re-)Downloading file taxdump.tar.gz

--2018-04-30 12:59:14--  ftp://ftp.ncbi.nih.gov/pub/taxonomy//taxdump.tar.gz
           => ‘/data/anaconda3/envs/basta/bin/BASTA/taxonomy/taxdump.tar.gz’
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 165.112.9.229, 2607:f220:41e:250::7
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|165.112.9.229|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy/ ... done.
==> SIZE taxdump.tar.gz ... 42837604
==> PASV ... done.    ==> RETR taxdump.tar.gz ... done.
Length: 42837604 (41M) (unauthoritative)

100%[===================================================================================================================================================================================================>] 42,837,604  6.14MB/s   in 9.8s

2018-04-30 12:59:25 (4.19 MB/s) - ‘/data/anaconda3/envs/basta/bin/BASTA/taxonomy/taxdump.tar.gz’ saved [42837604]

Traceback (most recent call last):
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/basta", line 117, in <module>
    main.run_basta(args)
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/BastaMain.py", line 75, in run_basta
    self._basta_taxonomy(args)
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/BastaMain.py", line 166, in _basta_taxonomy
    dutils.down_and_check("ftp://ftp.ncbi.nih.gov/pub/taxonomy/","taxdump.tar.gz",args.output)
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/DownloadUtils.py", line 56, in down_and_check
    down(ftp,md5,out_dir)
NameError: global name 'md5' is not defined
(basta) [user@hostname BASTA]$ /data/anaconda3/envs/basta/bin/BASTA/bin/basta download gb

##### Downloading and processing mapping file(s) from NCBI ###


# [BASTA STATUS] Downloading mapping files


# [BASTA STATUS] (Re-)Downloading file nucl_gb.accession2taxid.gz

--2018-04-30 13:00:03--  ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid//nucl_gb.accession2taxid.gz
           => ‘/data/anaconda3/envs/basta/bin/BASTA/taxonomy/nucl_gb.accession2taxid.gz’
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 165.112.9.228, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|165.112.9.228|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy/accession2taxid/ ... done.
==> SIZE nucl_gb.accession2taxid.gz ... 1009121640
==> PASV ... done.    ==> RETR nucl_gb.accession2taxid.gz ... done.
Length: 1009121640 (962M) (unauthoritative)

100%[=================================================================================================================================================================================================>] 1,009,121,640 15.4MB/s   in 2m 41s

2018-04-30 13:02:46 (5.97 MB/s) - ‘/data/anaconda3/envs/basta/bin/BASTA/taxonomy/nucl_gb.accession2taxid.gz’ saved [1009121640]

Traceback (most recent call last):
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/basta", line 117, in <module>
    main.run_basta(args)
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/BastaMain.py", line 71, in run_basta
    self._basta_download(args)
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/BastaMain.py", line 147, in _basta_download
    dutils.down_and_check(args.ftp,map_file,args.directory)
  File "/data/anaconda3/envs/basta/bin/BASTA/bin/../basta/DownloadUtils.py", line 56, in down_and_check
    down(ftp,md5,out_dir)
NameError: global name 'md5' is not defined
(basta) [user@hostname BASTA]$ ls ./taxonomy/
nucl_gb.accession2taxid.gz  prot.accession2taxid.gz  taxdump.tar.gz

**Comment by timkahlke** [comment]
Sigh, sorry, forgot to push the changes, getting late here.
Please do another git pull and retry.

**Comment by thierryjanssens** [comment]
Hi Tim,

I can make the lca work succesfully, but the creation of the Krona html file is still problematic, given the errors it is spitting out.

/data/anaconda3/envs/basta/bin/BASTA/scripts/basta2krona.py ./results/assembly-cl-lca-majority-l50.test ./assembly-cl-lca-majority-l50.html
Traceback (most recent call last):
  File "/data/anaconda3/envs/basta/bin/BASTA/scripts/basta2krona.py", line 81, in <module>
    main(args)
  File "/data/anaconda3/envs/basta/bin/BASTA/scripts/basta2krona.py", line 39, in main
    file_counts[f] = _parseBASTA(f)
  File "/data/anaconda3/envs/basta/bin/BASTA/scripts/basta2krona.py", line 68, in _parseBASTA
    counts[ls[1]] += 1
IndexError: list index out of range

regards,

Thierry

**Comment by timkahlke** [comment]
Hi Thierry,
I can't reproduce your error, the script seems to work fine for me.
The error indicates that your basta result file (assembly-cl-lca-majority-l50.test) is empty. Could you check if there is anything in there? And if so could you post the basta output file here?

If the file is empty please check the following:
1. Does the taxonomy folder contain the complete_taxa.gb folder and the gb_mapping.db folder?
2. If you used blast as the comparison tool: Is your basta input file tabular, i.e., produced with blast parameter -outfmt 6?
3. If you didn't use blast: is your custom file defining the columns correct?

**Comment by thierryjanssens** [comment]
Hi Tim,

the output of the lca is a file with expected content.

$ nano assembly-cl-lca-majority-l50.test

NODE_1_length_12698_cov_503.928498      Viruses;unknown;unknown;Mononegavirales;Paramyxoviridae;Respirovirus;Human_respirov$
;
NODE_2_length_6455_cov_180.445469       Viruses;unknown;unknown;unknown;Inoviridae;Inovirus;Escherichia_virus_M13;
;
NODE_3_length_5064_cov_77.414654        Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacterales;Enterobacteriaceae;Esc$
;
NODE_4_length_3304_cov_135.943059       Viruses;unknown;unknown;Picornavirales;Picornaviridae;Enterovirus;Rhinovirus_C;
;
NODE_6_length_2328_cov_15.786626        Viruses;unknown;unknown;Picornavirales;Picornaviridae;Enterovirus;Rhinovirus_C;
;

**Comment by timkahlke** [comment]
Hi Thierry,

The file you posted looks weird. Each line should have one gene/transcript identifier (in your case the NODE_X...) followed by a taxonomy string separated with a tab. Your file seems to include several special characters (e.g. the Esc$ and $), the ID and taxonomy string seem to be separated by spaces and it also includes lines that only contain a ";". This is why the krona script is confused.  

Could you post the sequence of commands you used to produce this file?

**Comment by thierryjanssens** [comment]
Hi Tim,

the weird characters were an artifact of nano.
The lca analysis was done as follows:
 /data/anaconda3/envs/basta/bin/BASTA/bin/basta sequence -t majority -l 50 ./data/assembly-nt-cl.tab ./results/assembly-cl-lca-majority-l50.test gb


head ./results/assembly-cl-lca-majority-l50.test
NODE_1_length_12698_cov_503.928498      Viruses;unknown;unknown;Mononegavirales;Paramyxoviridae;Respirovirus;Human_respirovirus_3;
;
NODE_2_length_6455_cov_180.445469       Viruses;unknown;unknown;unknown;Inoviridae;Inovirus;Escherichia_virus_M13;
;
NODE_3_length_5064_cov_77.414654        Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacterales;Enterobacteriaceae;Escherichia;Escherichia_coli;
;
NODE_4_length_3304_cov_135.943059       Viruses;unknown;unknown;Picornavirales;Picornaviridae;Enterovirus;Rhinovirus_C;
;
NODE_6_length_2328_cov_15.786626        Viruses;unknown;unknown;Picornavirales;Picornaviridae;Enterovirus;Rhinovirus_C;
;

**Comment by timkahlke** [comment]
The problem are the lines containing just the ";". I'm not sure where they come from, I can't reproduce the error. It could be a problem with the database as you had several attempts with downloading and parsing.  One way of checking that is to remove all the *.db directories from the taxonomy folder and re-do the basta taxonomy and download scripts.
