### ISSUE TITLE
Add LCA count

### ISSUE THREAD

**Issue by maxibor** [timkahlke/BASTA#13]
Hello @timkahlke ,
right now it is possible to get a count of hits per DB reference sequence (with the verbose flag), but **it is not possible to get a count of hits per LCA**, would it be doable to add it ?

Example:
```
###k79_72
11      Eukaryota;
11      Eukaryota;Streptophyta;
11      Eukaryota;Streptophyta;unknown;
11      Eukaryota;Streptophyta;unknown;Caryophyllales;
11      Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;
9       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Beta;
8       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Beta;Beta_vulgaris;
8       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Beta;Beta_vulgaris;
;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Beta;Beta_macrocarpa;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Beta;Beta_macrocarpa;
;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Chenopodium;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Chenopodium;Chenopodium_quinoa;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Chenopodium;Chenopodium_quinoa;
;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Spinacia;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Spinacia;Spinacia_oleracea;
1       Eukaryota;Streptophyta;unknown;Caryophyllales;Chenopodiaceae;Spinacia;Spinacia_oleracea;
;

```

Here the LCA would be `Chenopodiaceae` with 11 hits

--- 
What I'm doing on my side is combining the "regular" output of BASTA (that gives the LCA) and the "verbose" output of BASTA that gives count to get a count per LCA, but that's not really clean since I'm parsing both of these output files...

**Comment by timkahlke** [comment]
Hi Maxibor,

Sorry for the late reply. 
I included a -x flag that adds the amount of hits in brackets after the taxonomy in the regular basta output. Hope that makes the parsing obsolete :)
Let me know what you think

**Comment by timkahlke** [comment]
... btw: thanks for the changes but there was a but in the FileUtils (indentation was different). Guess I will have to start branching for versions :)

**Comment by maxibor** [comment]
I turned off the autopep8 on save of my editor :)
Thanks for the improvement, it seems to be working !
