### ISSUE TITLE
taxonomy classification of assembled genome bins

### ISSUE THREAD

**Issue by chloelulu** [timkahlke/BASTA#17]
Hi, developer,

Thanks for developing this amazing software. May I please know whether it can be used for taxonomy classification of a de novo assembled genome bin? Thank you!

**Comment by timkahlke** [comment]
Hi Chloe,
Yes, that's exactly one of the reasons why I wrote it :)

If you compare all contigs of one bin using Blast, BLAT, DIAMOND or whichever tool you prefer and then use that as input file for the `basta single` command you'll get the LCA for all the sequences in the input file. Alternatively, you could run `basta sequence` on it to see what the LCA for each contig is. This can help you to refine your bins by filtering out contigs with a very different taxonomy in comparison to the rest of the bin.

Tim

**Comment by chloelulu** [comment]
That is so amazing. I will have a try to run it on my data and have a look. Finger crossed!

**Comment by chloelulu** [comment]
Hi, @timkahlke ,
I am a little confusing about the usage of BASTA. After having read the wiki, I found it is used based on the blast/diamond/blat result file. Not on the individual bins. I am afraid  of the error usage. I have more than 200 assembled genome bins from maxbin2. So I want to define the taxonomy of these genome bins. I think I need to use `basta multiple`, correct? 
Thank you!

**Comment by timkahlke** [comment]
Hi Chloe,

That depends. For example, if you blast all contigs of one bin and then use the `basta single` command you will get one estimated taxonomy for the blast output file. BASTA will only take into account contigs that actually havve a blast hit to the database you used.

And you are right, if you have multiple blast output files in the same directory you can use the `basta multiple` command which basically applies `basta single` to each file.
