### ISSUE TITLE
Warning messages for mappings not found

### ISSUE THREAD

**Issue by arthurvinx** [timkahlke/BASTA#19]
Hi @timkahlke,

Is there some argument to hide the warning messages for mappings not found?

The printing of these warnings increases the time needed to finish the process (basta sequence).

**Comment by timkahlke** [comment]
Hi @arthurvinx,

No, unfortunately not. But I'll leave this one open and will add it to the next version. There will be a major re-write soon and I'll include a quite flag.

Thanks for the suggestion.
Tim

**Comment by timkahlke** [comment]
Finally included a "quiet" flag "-q True" which de-activates the messages.
