### ISSUE TITLE
INDEX ERROR

### ISSUE THREAD

**Issue by ilyavs** [timkahlke/BASTA#20]
Hi,
I ran blastn online, download the hits table as a csv and converted it to a tab delimited file. This is supposed to be required input for basta. However, I still get the following error:
```#### [BASTA ERROR] ####
#
# INDEX ERROR WHILE CHECKING e-value, alingment length OR percent  identity!!!.
# Are you sure that your input file has the correct format?
# (For details check https://github.com/timkahlke/BASTA/wiki/3.-BASTA-Usage#input-file-format)
#
#####
```

Please advise on how to fix this.
Thanks,
Ilya.

**Comment by timkahlke** [comment]
Hi Ilya,
That sounds a lot like a format error in the input file. Could you post your input file or parts of the tab delimited file you are suing, please?

Cheers,
Tim

**Comment by ilyavs** [comment]
Hi tim,
Please find attached a sample input.
Thanks,
Ilya.
[sample.tab.gz](https://github.com/timkahlke/BASTA/files/3516256/sample.tab.gz)

**Comment by timkahlke** [comment]
Hi Ilya,

The file looks ok and I can run it without problems, i.e., I can't reproduce your error. Can you check that there are no additional lines at the end or in the beginning of the complete file?
As the error message says: there is at least one line in your input file that is not a tab-separated line with 12 different values.

Cheers,
Tim

**Comment by ilyavs** [comment]
Hi Tim,
Thank you for pointing me in the right direction. The original full file contained two new lines at the end of the file which caused the issue. Once I removed them, all worked great.
Thank you,
Ilya.
