### ISSUE TITLE
UniProt database doesn't match Uniref90.fasta headers

### ISSUE THREAD

**Issue by Jigyasa3** [timkahlke/BASTA#22]
Hey @timkahlke 

I am running an LCA search for diamond blast output against the Uniref90 database using BASTA.
There are two things that I want to ask-
1. I first downloaded the NCBI protein database, and then the Uniprot database. But I got confused and deleted the prot.accession2taxid.gz file. The other mapping file and folder it generated were still intact before I downloaded the Uniprot database.
Would the absence of the prot.accession2taxid.gz file affect the BASTA search against the Uniprot database?

2.  After I got a no-match against the Uniprot database, I grepped some Uniref90 IDs from my blast output to idmapping_selected.tab.gz, and I couldn't find common IDs. 
Could you suggest a reason for that? 
I downloaded the latest version from https://www.uniprot.org/downloads

**Comment by timkahlke** [comment]
Hi @Jigyasa3,

1. deletion of the *.gz files shouldn't be a problem as the data is already stored in the databases. Actually, BASTA should delete those files after use to properly clean up ... not very tidy of me. Will be changed soon.

2. The problem there is that the Uniref databases have a slightly different header than the usual uniprot sequences. You can do several things to change that

a) Change the names of the sequences in the FastA file just after downloading it (before making the blast db out). To do so you could do 
`sed 's/UniRef90_//' UNIPROT.fasta > NEW.fasta`
where _UNIPROT.fasta_ is the uniref fasta file you donwloaded and _NEW.fasta_ is the edited one. Use the _NEW.fasta_ for all downstream analysis.

b) If you already blasted your sequences you could change the blast output file before using BASTA as follows
`sed 's/UniRef90_//' BLAST.out  > NEW_BLAST.out` 
and use the _New_BLAST.out_ as BASTA input.

Hope that helps,
Tim

**Comment by Jigyasa3** [comment]
Dear @timkahlke 

Thank you for the suggestion, it's working now!
