### ISSUE TITLE
Conda installation error

### ISSUE THREAD

**Issue by TomaszSuchan** [timkahlke/BASTA#25]
Conda installation on MacOS returns this error:
```
CondaVerificationError: The package for krona located at /Users/tomasz/miniconda3/pkgs/krona-2.7.1-pl526_1
appears to be corrupted. The path 'opt/krona/lib/._KronaTools.pm'
specified in the package manifest cannot be found.
```

**Comment by timkahlke** [comment]
It seems to be a problem with miniconda3. BASTA and Krona are python2 packages. In theory that shouldn't matter especially if you specify `python=2`. However, I wasn't able to install Krona (or BAST) using miniconda3. Miniconda2 installs without problems. Could you please try that? I'll port BASTA to python3 soon ... ish ...
