### ISSUE TITLE
question:is mapping database necessary?

### ISSUE THREAD

**Issue by genostack** [timkahlke/BASTA#26]
Hi,timkahlke
```
According to the doc,mapping database may be optional?
# download and set up genbank and uniprot mappings
# NOTE: this might not be needed for you. See Wiki for details
basta download gb
basta download prot
```

But when running BASTA mapping database must be set:
```
# Infer one LCA for each query sequence of blast against uniprot
basta sequence BLAST_OUTPUT_FILE BASTA_OUTPUT_FILE prot
# Infer one LCA for the complete blast output file
basta single BLAST_OUTPUT_FILE prot
# Infer one LCA for each blast output file in a given directory
basta multiple BLAST_OUTPUT_DIRECTORY BASTA_OUTPUT_FILE prot
```

I just want to use BASTA to do LCA from DIAMOND, must the mapping parameters needed? tks

**Comment by timkahlke** [comment]
Hi genostack,

A mapping database is required. However, you can create your own custom one, that's what I mean when I say you might not need to download one of the precompiled ones. Otherwise you will need a mapping database that maps your sequences to a taxonID.
