### ISSUE TITLE
how can I creat complete_taxa.db file use basta create_db? 

### ISSUE THREAD

**Issue by yuanpingdu** [timkahlke/BASTA#29]
Drear man,
    I have download taxdump files already, when I run basta sequence, it shows I should creat complete_taxa.db,  what should I need to do to creat complete_taxa.db ? I found a input file is need, but I don't kown to ues which file as input file .

**Comment by Echo-2024** [comment]
Hello! How do you creat **complete_taxa.db** with the file **taxdump.tar.gz**? I met the same problem and my **taxdump.tar.gz** were downloaded via wget  (md5 checked good) cause the **basta taxonomy** could not worked properly. Could you give me some advices? Thanks a lot.
