### ISSUE TITLE
Updates on Python 3 version?

### ISSUE THREAD

**Issue by bioinfoMMS** [timkahlke/BASTA#30]
Hi @timkahlke
Any updates on when a Python 3 version of BASTA will be available? I am hoping to use BASTA within a computational pipeline and would like to avoid having to replace BASTA when Python 2 becomes unsupported by my university's HPC.
Thanks!

**Comment by timkahlke** [comment]
Hi @bioinfoMMS,

Didn't work on it for months but this might be the reminder I needed. Let me see if I can get it done in the next 4 weeks.
Stay tuned ...

**Comment by bioinfoMMS** [comment]
That would be wonderful, thank you!

**Comment by bioinfoMMS** [comment]
Hi @timkahlke
Any updates on the python2 to python3 conversion?

**Comment by timkahlke** [comment]
Hi @bioinfoMMS 

It didn't become the grand re-write I planned but instead only a few bug fixes and making it python3 compliant. I'll see if I can check it in and put it up on bioconda this week.

**Comment by timkahlke** [comment]
Hi @bioinfoMMS ,

I'm not sure when I get it up on bioconda. However, it's all done, python3 compatible and tested. 
Follow the install instructions on the main page to install it in a conda environment.

**Comment by bioinfoMMS** [comment]
Excellent, thank you so much!
