### ISSUE TITLE
Basta2Krona output html file is empty. (help)

### ISSUE THREAD

**Issue by svsuresh** [timkahlke/BASTA#33]
Hi ! Thank you for the reply. I tried generating Krona chart with the script and basta output.  Krona (output) html is empty.

```
 $ head Basta_output.tsv 

contig_48	Unknown	Eukaryota;Arthropoda;Insecta;Coleoptera;Carabidae;Amara;Amara_sp._KAO-2002;
contig_65	Unknown	Eukaryota;Arthropoda;Insecta;Coleoptera;Carabidae;Amara;Amara_alpina;
contig_117	Unknown	Eukaryota;Arthropoda;Insecta;Hymenoptera;Vespidae;Vespula;Vespula_pensylvanica;
contig_130	Unknown	Unknown
contig_214	Unknown	Viruses;unknown;unknown;unknown;Polydnaviridae;Bracovirus;Cotesia_sesamiae_bracovirus;
contig_375	Unknown	Eukaryota;Arthropoda;Insecta;Coleoptera;Carabidae;Zabrus;Zabrus_ignavus;
contig_408	Viruses;Phixviricota;Malgrandaviricetes;Petitvirales;Microviridae;Sinsheimervirus;Escherichia_virus_phiX174;	Viruses;Phixviricota;Malgrandaviricetes;Petitvirales;Microviridae;Sinsheimervirus;Escherichia_virus_phiX174;
contig_565	Unknown	Eukaryota;Arthropoda;Insecta;Coleoptera;Carabidae;Amara;Amara_alpina;
contig_597	Unknown	Eukaryota;Arthropoda;Insecta;Coleoptera;Zopheridae;Verodes;Verodes_sp._nov._C_ER-2011;
contig_619	Unknown	Eukaryota;Arthropoda;Insecta;Lepidoptera;Bombycidae;Bombyx;Bombyx_mori;

```

Command:
```
$ python3 basta2krona.py Basta_output.tsv Krona.html
```
I would appreciate if you could share an example working output so that I can troubleshoot output I have. Link to download the output file I have : https://docs.google.com/spreadsheets/d/1gIrihuvNo2mV3X0JgQGsKaCuiPd4Xp2IyAKZfLYpY6Q/edit?usp=sharing. Link contains a tsv file from personal gmail account.

`

**Comment by timkahlke** [comment]
Hi @svsuresh,

First, your input file includes not just sequence name and taxon but also the best hit in the third column. However, as mentioned before, basta expects a 2 column file: col1 = sequence name, col2 = taxon. If you wanted to plot the best hit you could just remove the second column and take the third as taxon column. This would produce a "best hit" krona plot


That said, I cannot reproduce the empty file. For me basta2krona works. Even the 3 column file you posted above produces an html file that shows krona plots.
