### ISSUE TITLE
database creation issue for uniprot e.g. type uni

### ISSUE THREAD

**Issue by shrivastavabhishek** [timkahlke/BASTA#34]
Hi @timkahlke 
I was running basta download -d /mnt/Indices/genomes/basta/taxonomy/ uni to download uniprot database. It is downloading the idmapping_selected.tab and creating the database with name "prot_mapping.db".

After this, I am running basta sequence dataset_19472.txt dataset_19493.txt uni --directory /mnt/Indices/genomes/basta/taxonomy/

[BASTA ERROR] No database uni_mapping.db found in /mnt/Indices/genomes/basta/taxonomy/. Did you forget to create the specified.

Please let me know the reason of failure.

**Comment by timkahlke** [comment]
H @shrivastavabhishek,

No worries, the type for uniprot is also "prot" not "uni". So your call should be `basta sequence dataset_19472.txt dataset_19493.txt prot --directory /mnt/Indices/genomes/basta/taxonomy`.

The "uni" is only used for download of the mapping file. As mentioned in the Wiki, uniprot mapping is still imported into the protein database: 

> uni - uniprot-to-taxonID mapping file (complete uniprot, will also be imported into database prot)

Hope this helps

**Comment by shrivastavabhishek** [comment]
Thanks @timkahlke !!!
