### ISSUE TITLE
Which mapping file for NR database

### ISSUE THREAD

**Issue by zhuxiaoyu123** [timkahlke/BASTA#35]
Hi,

If i use NR database, which mapping file should i download?

Thanks

**Comment by timkahlke** [comment]
Hi,

for nucleotide should be "gb".

Cheers

**Comment by zhuxiaoyu123** [comment]
Hi,

NR is protein database, i think prot may be the right one.

Cheers

**Comment by timkahlke** [comment]
Sorry, I somehow read "nt" instead of "nr". Yes, prot is the one you want.

**Comment by zhuxiaoyu123** [comment]
OK. Appreciate that.
