### ISSUE TITLE
Multi thread usage

### ISSUE THREAD

**Issue by Fu-Yin** [timkahlke/BASTA#37]
Hello:
My diamond output an file, which about 10 g, and I next to use the BASTA to estimate spices in it.
However, BASTA  has been worked 10 days.
Could BASTA  use more threads to make it faster.
What can I do to faster?
Thanks

**Comment by timkahlke** [comment]
Hi,
First, to answer your question: no, there is no multi-threaded BASTA available. However, BASTA doesn't use a lot of resources and doesn't do complicated calculations or the like. It's a pretty simple method. I ran BASTA on much larger files in a few hours. Something else is going on there.

**Comment by Fu-Yin** [comment]
Thank you for your answer
Can I watch your command? Maybe I took a wrong use.
