### ISSUE TITLE
[BASTA ERROR] Couldn't find complete_taxa.db in /work/uniprot Did you run initial 'basta download'?

### ISSUE THREAD

**Issue by Adamyazori** [timkahlke/BASTA#38]
Hi!
I am trying to assign taxonomy to a diamond blastp results using basta. 
I downloaded the protein (prot) database using basta download prot.
In the database directory I have these two files: prot.accession2taxid.gz.md5, prot.accession2taxid.gz and the 
prot_mapping.db folder. 

I kept getting an error, looks like basta is looking for a db called complete_taxa.db.
Is there something that am missing in my command????

thank you

**Comment by timkahlke** [comment]
Hi,

Did you also download the NCBI taxonomy using the `basta taxonomy` command? You need 2 things

1. The NCBI taxonomy downloaded with `basta taxonomy`, which creates the complete_taxa.db
2. A mapping file, e.g., a protein mapping file that maps a protein ID to an NCBI taxonomy. That's what you already got in your prot_mapping.db folder.

Hope this solves it.

**Comment by Adamyazori** [comment]
oook. Alright thanks so much.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
08/20/22,
10:41:48 AM

**Comment by Echo-2024** [comment]
Hello! How do you creat complete_taxa.db with the file taxdump.tar.gz? 
I met the same problem and my taxdump.tar.gz were downloaded via wget (md5 checked good) cause the basta taxonomy could not worked properly. Could you give me some advices? Thanks a lot.

I am also trying to assign taxonomy to a diamond blastp results using basta.
In the database directory I have these two files: taxdump.tar.gz, prot.accession2taxid.gz and the prot_mapping.db folder.
